train_data:
  sample_id: Spatial_CITEseq_Tonsil1
  hires_image_key: CytAssist_FFPE_Protein_Expression_Human_Tonsil

test_data:
  sample_id: Spatial_CITEseq_Tonsil2
  hires_image_key: CytAssist_FFPE_Protein_Expression_Human_Tonsil_AddOns

image_model:
  hf_repo_id: 'google/vit-base-patch16-224-in21k'
  pretrained: true
  freeze_parameters: false
  use_predictions_as_features: false

model:
  graph_layer: 'GAT' # GCN, GAT
  gat_heads: 4
  fusion_method: 'concat' # concat, gated
  gene_hidden_dim: 256

hyperparameters:
  train_batch_size: 128
  test_batch_size: 128
  patch_size: 256
  epochs: 100
  learning_rate: 0.001
  target_num_genes: 2000
  random_seed: 42
  use_validation: false
  graph_k: 7

logging:
  use_wandb: true
  wandb_project: 'spatial_transcriptomics_hf'
  wandb_name: 'vit-base-16-in21k-k7-concat'
