h5_file_path: tonsil1_filtered_feature_bc_matrix.h5
sample_id: Spatial_CITEseq_Tonsil1
hires_image_key: CytAssist_FFPE_Protein_Expression_Human_Glioblastoma
patch_size: 128
batch_size: 32
epochs: 50
learning_rate: 0.001
target_num_genes: 5000
use_wandb: True
wandb_project: 'spatial_transcriptomics'
wandb_entity: 'mpekey'
evaluation_metrics: ['RMSE', 'MAE', 'pearson_correlation', 'spearman_correlation']
random_seed: 42
