sample_id: Spatial_CITEseq_Tonsil1
hires_image_key: CytAssist_FFPE_Protein_Expression_Human_Tonsil
patch_size: 32
batch_size: 4
epochs: 2
learning_rate: 0.001
target_num_genes: 50
use_wandb: false
wandb_project: 'spatial_transcriptomics'
wandb_name: 'debug_cnn'
evaluation_metrics: ['RMSE', 'MAE', 'pearson_correlation', 'spearman_correlation']
random_seed: 42
