train_data:
  sample_id: Spatial_CITEseq_Tonsil1
  hires_image_key: CytAssist_FFPE_Protein_Expression_Human_Tonsil

test_data:
  sample_id: Spatial_CITEseq_Tonsil2
  hires_image_key: CytAssist_FFPE_Protein_Expression_Human_Tonsil_AddOns

image_model:
  model_type: 'resnet'
  model_name: ''
  pretrained: true
  freeze_parameters: false

hyperparameters:
  train_batch_size: 128
  test_batch_size: 128
  patch_size: 256
  epochs: 100
  learning_rate: 0.001
  target_num_genes: 2000
  random_seed: 42
  use_validation: true

logging:
  use_wandb: true
  wandb_project: 'spatial_transcriptomics'
  wandb_name: 'resnet18'
